---
aspera_apt_apps:
  - libreoffice-writer
  - libreoffice-calc
  - libreoffice-draw
  - simplescreenrecorder
  - flameshot
aspera_purge_apps:
  - hypnotix
  - thunderbird
  - thunderbird-gnome-support
  - hexchat
  - transmission-gtk
  - drawing
  - warpinator
  - gnome-mines
  - gnome-sudoku
  - rhythmbox
  - firefox
  - firefox-locale-en
  - libreoffice-base
  - libreoffice-impress
  - libreoffice-math
  - mintstick
  - xfce4-notes
  - xfce4-screenshooter
  - webapp-manager
  - celluloid
  - vlc
  - element-desktop
  - fractal
  - nheko
