---
aspera_apt_apps:
  - libreoffice-writer
  - libreoffice-calc
  - libreoffice-impress
  - libreoffice-draw
  - simplescreenrecorder
  - flameshot
  - xfce4-screenshooter
  - vlc
aspera_purge_apps:
  - hypnotix
  - thunderbird
  - hexchat
  - transmission-gtk
  - drawing
  - warpinator
  - gnome-mines
  - gnome-sudoku
  - rhythmbox
  - firefox
  - libreoffice-base
  - libreoffice-math
  - mintstick
  - xfce4-notes
  - webapp-manager
  - celluloid
