---
- name: Hide software store launchers
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "NoDisplay=true"
    create: false
  loop:
    - /usr/share/applications/mintinstall.desktop
    - /usr/share/applications/ubuntu-software.desktop
  failed_when: false

- name: Brand os pretty name
  ansible.builtin.lineinfile:
    path: /etc/os-release
    regexp: '^PRETTY_NAME='
    line: 'PRETTY_NAME="Aspera OS 1.0"'
